on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release_version:
    runs-on: ubuntu-latest
    name: Release lib version
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          app-name: 'plugin-sdk'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm i --save-dev conventional-changelog-conventionalcommits@v6.1.0 @semantic-release/github

      - name: Release version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}